### PR TITLE
Alternate allocate_memory

### PR DESCRIPTION
**Pull request by JMazzu**
Create a buffer passed by reference, rather than returning a reference.

### CODE REVIEW

**Comment by melrobin** [comment]
Standard C does not use // for comments.  I'm not sure that this comment style will work with all compilers.  Otherwise the request is good.  Thoughts?

**Comment by JMazzu** [comment]
I thought I remembered that about C89. I assumed it was fine after gcc compiled it.
For my money, I'd rather return the `double *`, so our malloc wrapper acts as much as possible like malloc.

**Review by melrobin — CHANGES_REQUESTED** [review]
Convert to standard comment syntax.

**Comment by JMazzu** [comment]
ok

**Review by melrobin — APPROVED** [review]

**Pull request merged**
